on:
  push:
    branches: 
     - main
  
  pull_request:
    types: [opened, synchronize,reopened]

name : Main Workflows
jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: stackhawk/hawkscan-action@v1.3.2
      with:
        apiKey: ${{ secrets.HAWK_API_KEY }}
        codeScanningAlerts: true
        configurationFiles: |
          stackhawk.yml

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
