on:
  push:
    branches: [main]
  
  pull_request:
    branches: [main]
 
  discussion:
    types: [created, edited, answered]
  
  issues:
    types: [opened, edited, milestoned]
  
  label:
    types: [created, deleted]
  
  schedule:
    - cron: '25 7 * * 4'

name : Main Workflows
jobs:
  specific_review_requested:
    runs-on: ubuntu-latest
    if: ${{ github.event.requested_team.name == 'ichsan-team'}}
    steps:
      - run: echo 'A review from ichsan-team was requested'

  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build Docker image
      run: docker build . --file Dockerfile --tag apigo:$(date +%s)

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
      with:
         heroku_api_key: ${{secrets.HEROKU_API_KEY}}
         heroku_app_name: "bmiupdate-calce" #Must be unique in Heroku
         heroku_email: "ichsanbahri91@gmail.com"
    
    - name: Owasp ZAP
      uses: zaproxy/action-baseline@v0.6.1
      with:
       token: ${{ secrets.GITHUB_TOKEN }}
       docker_name: 'owasp/zap2docker-stable'
       target: 'https://protected-harbor-67469.herokuapp.com/'
       rules_file_name: '.zap/rules.tsv'
       cmd_options: '-a'
        