on:
  push:
    branches: 
     - main
  
  pull_request:
    branches:
    - main

    types: [opened, synchronize,reopened]

name : Main Workflows
jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
    
    - name: Owasp Zap Baseline Scan
      uses: zaproxy/action-baseline@v0.3.0
      with:
        target: "https://protected-harbor-67469.herokuapp.com/"
        