on:
  push:
    branches: [main]
  
  pull_request:
    branches: [main]
 
  discussion:
    types: [created, edited, answered]
  
  issues:
    types: [opened, edited, milestoned]
  
  label:
    types: [created, deleted]
  
  schedule:
    - cron: '25 7 * * 4'

name : Main Workflows
jobs:
  specific_review_requested:
    runs-on: ubuntu-latest
    if: ${{ github.event.requested_team.name == 'ichsan-team'}}
    steps:
      - run: echo 'A review from ichsan-team was requested'

  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build Docker image
      run: docker build . --file Dockerfile --tag apigo:$(date +%s)

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
      with:
         heroku_api_key: ${{secrets.HEROKU_API_KEY}}
         heroku_app_name: "bmiupdate-calce" #Must be unique in Heroku
         heroku_email: "ichsanbahri91@gmail.com"

      # Execute Codacy Analysis CLI and generate a SARIF output with the security issues identified during the analysis
    - name: Run Codacy Analysis CLI
      uses: codacy/codacy-analysis-cli-action@d840f886c4bd4edc059706d09c6a1586111c540b
      with:
          # Check https://github.com/codacy/codacy-analysis-cli#project-token to get your project token from your Codacy repository
          # You can also omit the token and run the tools that support default configurations
        project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
        verbose: true
        output: results.sarif
        format: sarif
          # Adjust severity of non-security issues
        gh-code-scanning-compat: true
          # Force 0 exit code to allow SARIF file generation
          # This will handover control about PR rejection to the GitHub side
        max-allowed-issues: 2147483647

    - name: Run Gosec Security Scanner
      uses: securego/gosec@master
      with:
         args: '-no-fail -fmt sarif -out results.sarif ./...'
    
    - name: Upload SARIF results file
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: results.sarif
    
    - name: Owasp ZAP
      uses: zaproxy/action-baseline@v0.6.1
      with:
       token: ${{ secrets.GITHUB_TOKEN }}
       docker_name: 'owasp/zap2docker-stable'
       target: 'https://bmiupdate-calce.herokuapp.com/'
       rules_file_name: '.zap/rules.tsv'
       cmd_options: '-a'
        